# timeout
timeout = "1200s"
# your website url
baseURL = 'https://purpfolio.netlify.app/'
# website title
title = 'Purpfolio'
# don't touch this
disableKinds = ["section", "taxonomy", "term"]
# robots.txt
enableRobotsTXT = true

# available options
# * en (powered by Geist)
# * de (powered by Geist)
# * es (powered by Geist)
# * fr (powered by Geist)
# * it (powered by Geist)
# * zh-sg zh-cn (powered by Noto Sans SC)
# * zh-hk zh-tw zh-mo (powered by Noto Sans TC)
# * ja (powered by Noto Sans JP)
# * ko (powered by Noto Sans KR)
defaultContentLanguage = 'it'

# config/_default/hugo.toml
[module]
[[module.imports]]
path = "github.com/Sped0n/bridget/v2"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "JSON"]
  page = ["HTML", "JSON"]
